# Use the spec.group/spec.versions[0].name defined in the XRD
apiVersion: xplane.sijoma.io/v1alpha1
# Use the spec.claimName or spec.name specified in the XRD
kind: EncryptionKey
metadata:
  # Only claims are namespaced, unlike XRs.
  namespace: default
  name: managed-encryption-key
spec:
  # The compositionRef specifies which Composition this XR will use to compose
  # resources when it is created, updated, or deleted.
  compositionRef:
    name: encryptionkey-composition

  # Parameters for the Composition to provide the Managed Resources (MR) with
  # to create the actual infrastructure components
  protectionLevel: SOFTWARE
